package com.example.demo.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import java.util.UUID;

@Entity(name = "gcp_mod_control")
@Getter
@Setter
@NoArgsConstructor
public class GCPModControl {
  /** Primary key. */
  protected static final String PK = "index";

  @Column(columnDefinition = "uuid default uuid_generate_v4 ()")
  private UUID index = UUID.randomUUID();

  @JsonIgnore private String args;

  @Column(name = "auto_generated", length = 1)
  @JsonIgnore
  private boolean autoGenerated;

  @Column(columnDefinition = "text")
  private String description;

  @JsonIgnore
  @Column(columnDefinition = "text")
  private String documentation;

  @Column(name = "end_line_number", precision = 19)
  @JsonIgnore
  private long endLineNumber;

  @Column(name = "file_name", columnDefinition = "text")
  @JsonIgnore
  private String fileName;

  @Column(name = "mod_name", columnDefinition = "text")
  private String modName;

  @JsonIgnore
  @Column(columnDefinition = "text")
  private String params;

  @Id
  @Column(name = "resource_name", columnDefinition = "text")
  private String resourceName;

  @Column(columnDefinition = "text")
  private String severity;

  @JsonIgnore
  @Column(name = "source_definition", columnDefinition = "text")
  private String sourceDefinition;

  @Column(columnDefinition = "text")
  private String sql;

  @JsonIgnore
  @Column(name = "start_line_number", precision = 19)
  private long startLineNumber;

  @JsonIgnore
  @Column(columnDefinition = "text")
  private String tags;

  @Column(columnDefinition = "text")
  private String title;

  @Column private boolean isAnonymous;

  @Column(columnDefinition = "text")
  private String path;

  @Column(columnDefinition = "text")
  private String qualifiedName;

  @Column(columnDefinition = "text")
  private String query;
}
